<?php
/**
 * Created by PhpStorm.
 * User: Андрей
 * Date: 24.09.2018
 * Time: 15:21
 */

namespace App;


use Illuminate\Database\Eloquent\Model;

class Alevel_member extends Model
{
    protected $fillable = [
        'person_id',
        'ASPT',
        'position_id',
        'direction_id',
        'company_id',
        'comment',
    ];

    public function getQueueableRelations()
    {
        // TODO: Change the autogenerated stub
    }

    public function persons()
    {
        return $this->hasOne('App\Person');
    }
    public function positions()
    {
        return $this->belongsTo('App\Position');
    }

    public function directions()
    {
        return $this->belongsTo('App\Direction');
    }

    public function it_companies()
    {
        return $this->belongsTo('App\It_company');
    }

    public function students()
    {
        return $this->hasMany('App\Student');
    }
}
