<?php
/**
 * Created by PhpStorm.
 * User: Андрей
 * Date: 24.09.2018
 * Time: 15:21
 */

namespace App;


use Illuminate\Database\Eloquent\Model;

class Alevel_member extends Model
{
    protected $fillable = [
        'person_id' => 'integer',
        'ASPT' => 'bool',
    ];

    public function getQueueableRelations()
    {
        // TODO: Change the autogenerated stub
    }
}
