<?php
/**
 * Created by PhpStorm.
 * User: Андрей
 * Date: 24.09.2018
 * Time: 15:23
 */

namespace App;


use Illuminate\Database\Eloquent\Model;

class Contact_person extends Model
{
    protected $table = 'contact_persons';

    protected $fillable = [
        'person_id' => 'integer',
        'position_id' => 'integer',
        'direction_id' => 'integer',
        'company_id' => 'integer',
        'comment',
    ];

    public function getQueueableRelations()
    {
        // TODO: Change the autogenerated stub
    }

    public function person()
    {
        return $this->belongsTo('App\Person');
    }

    public function positions()
    {
        return $this->belongsTo('App\Position');
    }

    public function directions()
    {
        return $this->belongsTo('App\Direction');
    }

    public function it_companies()
    {
        return $this->belongsToMany('App\It_company');
    }
}
