<?php
/**
 * Created by PhpStorm.
 * User: Андрей
 * Date: 24.09.2018
 * Time: 15:23
 */

namespace App;


use Illuminate\Database\Eloquent\Model;

class Contact_person extends Model
{
    protected $fillable = [
        'person_id' => 'integer',
    ];

    public function getQueueableRelations()
    {
        // TODO: Change the autogenerated stub
    }
}
