<?php
/**
 * Created by PhpStorm.
 * User: Андрей
 * Date: 24.09.2018
 * Time: 15:23
 */

namespace App;


use Illuminate\Database\Eloquent\Model;

class Direction extends Model
{
    protected $fillable = [
        'direction',
    ];

    public function getQueueableRelations()
    {
        // TODO: Change the autogenerated stub
    }

    public function alevel_members()
    {
        return $this->hasMany('App\Alevel_member');
    }

    public function groups()
    {
        return $this->hasMany('App\Group');
    }

    public function contact_persons()
    {
        return $this->hasMany('App\Contact_person');
    }

//    public function students()
//    {
//        return $this->hasMany('App\Student');
//    }
}
