<?php
/**
 * Created by PhpStorm.
 * User: Андрей
 * Date: 24.09.2018
 * Time: 15:24
 */

namespace App;


use Illuminate\Database\Eloquent\Model;

class Employment_student extends Model
{
    protected $fillable = [
        'student_id',
        'company_id',
        'comment',
    ];

    public function getQueueableRelations()
    {
        // TODO: Change the autogenerated stub
    }
}
