<?php
/**
 * Created by PhpStorm.
 * User: Андрей
 * Date: 24.09.2018
 * Time: 15:24
 */

namespace App;


use Illuminate\Database\Eloquent\Model;

class Group extends Model
{
    protected $fillable = [
        'group_name',
        'start_date' => 'date',
        'finish_date',
        'homecoming_date',
        'direction_id',
    ];

    public function getQueueableRelations()
    {
        // TODO: Change the autogenerated stub
    }

}
