<?php
/**
 * Created by PhpStorm.
 * User: Андрей
 * Date: 24.09.2018
 * Time: 15:25
 */

namespace App;

use Illuminate\Database\Eloquent\Model;

class It_company extends Model
{
    protected $table = 'it_companies';

    protected $fillable = [
        'company_name',
        'status',
        'type',
        'site',
        'comment',
        'address',
        'logo',
    ];

    public function getQueueableRelations()
    {
        // TODO: Change the autogenerated stub
    }
}
