<?php
/**
 * Created by PhpStorm.
 * User: Андрей
 * Date: 24.09.2018
 * Time: 15:25
 */

namespace App;

use Illuminate\Database\Eloquent\Model;

class It_company extends Model
{
    protected $table = 'it_companies';

    protected $fillable = [
        'company_name',
        'status',
        'type',
        'site',
        'comment',
        'address',
        'logo',
    ];

    public function getQueueableRelations()
    {
        // TODO: Change the autogenerated stub
    }

    public function alevel_members()
    {
        return $this->hasMany('App\Alevel_member');
    }

    public function stack_groups()
    {
        return $this->hasMany('App\Stack_groups');
    }

    public function contact_persons()
    {
        return $this->hasMany('App\Contact_person');
    }

    public function students()
    {
        return $this->hasMany('App\Student');
    }
}
