<?php
/**
 * Created by PhpStorm.
 * User: Андрей
 * Date: 24.09.2018
 * Time: 15:25
 */

namespace App;

use Illuminate\Database\Eloquent\Model;

class Person extends Model
{
    protected $table = 'persons';

    protected $fillable = [
        'name',
        'address',
    ];

    public static function find($id)
    {
    }

    public function getQueueableRelations()
    {
        // TODO: Change the autogenerated stub
    }

    public function contacts()
    {
        return $this-> hasMany('App\Contact');
    }

    public function students()
    {
        return $this->hasMany('App\Students');
    }

    public function skill_groups()
    {
        return $this->belongsToMany('App\Skill_group');
    }

    public function contact_persons ()
    {
        return $this->hasMany('App\Contact_person');
    }

    public function alevel_members()
    {
        return $this->belongsTo('App\Alevel_member');
    }
}
