<?php
/**
 * Created by PhpStorm.
 * User: Андрей
 * Date: 24.09.2018
 * Time: 15:28
 */

namespace App;


use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = [
        'learning_status',
        'employment_status',
        'group_id' => 'integer',
        'position_id' => 'integer',
        'company_id' => 'integer',
        'member_id' => 'integer',
        'person_id' => 'integer',
        'CV',
        'comment',
    ];

    public static function find($id)
    {
    }

    public function getQueueableRelations()
    {
        // TODO: Change the autogenerated stub
    }

    public function person()
    {
        return $this->belongsTo('App\Person');
    }

    public function positions()
    {
        return $this->belongsTo('App\Position');
    }

    public function directions()
    {
        return $this->belongsTo('App\Direction');
    }

    public function it_companies()
    {
        return $this->belongsTo('App\It_company');
    }

    public function alevel_members()
    {
        return $this->belongsTo('App\Alevel_member');
    }

    public function groups()
    {
        return $this->belongsTo('App\Group');
    }
}
