<?php
/**
 * Created by PhpStorm.
 * User: Андрей
 * Date: 24.09.2018
 * Time: 15:28
 */

namespace App;


use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = [
        'learning_status',
        'employment_status',
        'group_id' => 'integer',
    ];

    public function getQueueableRelations()
    {
        // TODO: Change the autogenerated stub
    }
}
